### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by voylin** [VoylinsGamedevJourney/GoZen#93]
### Problem or limitation

# Roadmap for GoZen
## Alpha
Everything which needs to be done before the alpha can be released.
### To Do's:
- [ ] **[Timeline]** Clips data structure;
- [ ] **[Timeline]** Clips saving/loading;
- [ ] **[Timeline]** Clip cutting;
- [ ] **[Timeline]** Clip moving;
- [ ] **[Timeline]** Clip resizing;
- [ ] **[Timeline]** Clip moving (in same track + multi track);
- [ ] **[Timeline]** Make the play-head work;
- [ ] **[Timeline]** Display time positions on top;
- [ ] **[Project View]** Display what the play-head is on;
- [ ] **[Project View]** Display audio meter;
- [ ] **[Project View]** Basic playback controls;
- [ ] **[Effects]** Basic audio volume effect;
- [ ] **[Effects]** Basic fade;
- [ ] **[Effects]** Basic transforms (position, scale, size, rotation);
- [ ] **[Effects]** Give files basic effects by default;
- [ ] **[Effects]** In effects panel display both file effects and clip effects;
- [ ] **[Renderer]** Have render export video frames from timeline;
- [ ] **[Renderer]** Have render export audio data from timeline;
- [ ] **[Renderer]** Basic render presets;
- [ ] **[Renderer]** Option to render specific area of timeline;

## Beta
Everything which needs to be done before the beta can be released.
### To Do's:
- [ ] **[Build system]** Have an automated build system working;
- [ ] **[Effects]** Have effect times to have more dynamic effects;
- [ ] **[Transitions]** Create a basic transition which can be applied to timeline;
- [ ] **[Shortcut handler]** Have the shortcut handler set up;
- [ ] **[Core]** Have undo and redo working correctly;
- [ ] **[Subtitle layout]** Have a working subtitle handler layout;
- [ ] **[Dialog manager]** Have a custom dialog window for opening/selecting/saving files;

## First release
Everything which needs to be done before GoZen can finally be released.
### To Do's:
- [ ] **[Core]** No crashes;
- [ ] **[Core]** All alpha+beta bugs fixed;
- [ ] **[Build system]** Working Linux build;
- [ ] **[Build system]** Linux installer;
- [ ] **[Build system]** Add to pacman? (not certain how easy or if possible at all);
- [ ] **[Build system]** Working Windows build;
- [ ] **[Build system]** Windows installer;
- [ ] **[Module garden]** Have the module garden basics setup;

### Feature / enhancement to solve the problem

dd
